/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewGUI;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfian R7
 */
public class AllMenus extends javax.swing.JFrame implements View{

    /**
     * Creates new form AllMenus
     */
    public AllMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnViewAnggota = new javax.swing.JButton();
        BtnBarang = new javax.swing.JButton();
        BtnPeminjaman = new javax.swing.JButton();
        BtnAddPinjaman = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnViewAnggota.setText("View Anggota");

        BtnBarang.setText("View Barang");

        BtnPeminjaman.setText("View Pinjaman");
        BtnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPeminjamanActionPerformed(evt);
            }
        });

        BtnAddPinjaman.setText("ADD Pinjaman");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Inventaris Peminjaman Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnViewAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(BtnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(BtnPeminjaman))))
                .addGap(49, 49, 49)
                .addComponent(BtnAddPinjaman)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(BtnViewAnggota)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBarang)
                    .addComponent(BtnAddPinjaman))
                .addGap(29, 29, 29)
                .addComponent(BtnPeminjaman)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPeminjamanActionPerformed


    public Object getBtnAddPinjaman(){
        return BtnAddPinjaman;
    }
    
    public Object getBtnBarang(){
        return BtnBarang;
    }
    
    public Object getPeminjaman(){
        return BtnPeminjaman;
    }
    
    public Object getAnggota(){
        return BtnViewAnggota;
    }
    
    @Override
    public void addListener(ActionListener e){
        BtnAddPinjaman.addActionListener(e);
        BtnBarang.addActionListener(e);
        BtnPeminjaman.addActionListener(e);
        BtnViewAnggota.addActionListener(e);
    }
    
    public void ViewErrorMsg(String errMsg){
        JOptionPane.showMessageDialog(this, errMsg);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddPinjaman;
    private javax.swing.JButton BtnBarang;
    private javax.swing.JButton BtnPeminjaman;
    private javax.swing.JButton BtnViewAnggota;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
