/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewGUI;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfian R7
 */
// Created by:
// Nama     :Alfian Rahman Aziz
// NIM      : 1301150063
public class AllMenus extends javax.swing.JFrame implements View{

    /**
     * Creates new form AllMenus
     */
    public AllMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnViewAnggota = new javax.swing.JButton();
        BtnBarang = new javax.swing.JButton();
        BtnPeminjaman = new javax.swing.JButton();
        BtnAddPinjaman = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JButton();
        BtnAddBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnViewAnggota.setText("View Anggota");

        BtnBarang.setText("View Barang");

        BtnPeminjaman.setText("View Pinjaman");
        BtnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPeminjamanActionPerformed(evt);
            }
        });

        BtnAddPinjaman.setText("ADD Pinjaman");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Inventaris Peminjaman Barang");

        BtnLogout.setText("Logout");

        BtnAddBarang.setText("ADD Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnPeminjaman)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnViewAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnAddPinjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAddBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewAnggota)
                    .addComponent(BtnAddBarang))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBarang)
                    .addComponent(BtnAddPinjaman))
                .addGap(27, 27, 27)
                .addComponent(BtnPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPeminjamanActionPerformed

    public Object getBtnLogout(){
        return BtnLogout;
    }
    public Object getBtnAddPinjaman(){
        return BtnAddPinjaman;
    }
    
    public Object getBtnBarang(){
        return BtnBarang;
    }
    
    public Object getBtnPeminjaman(){
        return BtnPeminjaman;
    }
    
    public Object getBtnAnggota(){
        return BtnViewAnggota;
    }
    
    public Object getBtnAddBarang(){
        return BtnAddBarang;
    }
    
    @Override
    public void addListener(ActionListener e){
        BtnAddPinjaman.addActionListener(e);
        BtnBarang.addActionListener(e);
        BtnPeminjaman.addActionListener(e);
        BtnViewAnggota.addActionListener(e);
        BtnLogout.addActionListener(e);
        BtnAddBarang.addActionListener(e);
    }
    
    @Override
    public void ViewErrorMsg(String errMsg){
        JOptionPane.showMessageDialog(this, errMsg);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddBarang;
    private javax.swing.JButton BtnAddPinjaman;
    private javax.swing.JButton BtnBarang;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnPeminjaman;
    private javax.swing.JButton BtnViewAnggota;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
